AWSTemplateFormatVersion: 2010-09-09
Description: >
  GitSync-enabled CloudFormation template to create IAM groups, users, and a one-time password stored in Secrets Manager.

Resources:

  OTPSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: OneTimePassword
      Description: One-time password for IAM users
      GenerateSecretString:
        PasswordLength: 12
        ExcludeCharacters: "\"@/\\` '"
        RequireEachIncludedType: true

  S3ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: S3ReadOnlyGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  EC2ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: EC2ReadOnlyGroup
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: s3-user
      Groups:
        - !Ref S3ReadOnlyGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${OTPSecret}::SecretString}}'
        PasswordResetRequired: true

  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: ec2-user
      Groups:
        - !Ref EC2ReadOnlyGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${OTPSecret}::SecretString}}'
        PasswordResetRequired: true

Outputs:
  OTPSecretArn:
    Description: ARN of the stored one-time password in Secrets Manager
    Value: !Ref OTPSecret

  S3UserConsoleLogin:
    Description: S3 User Console Login Name
    Value: s3-user

  EC2UserConsoleLogin:
    Description: EC2 User Console Login Name
    Value: ec2-user
